<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="appsettings.Local.json" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="appsettings.Local.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
	<!--<PackageReference Include="Archipelago.Core" Version="1.2.3" />-->
	<ProjectReference Include="D:\Archipelago\dev\Archipelago.Core\Archipelago.Core.csproj" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.1" />
    <PackageReference Include="Kokuban" Version="0.2.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Enums\" />
    <Folder Include="Models\" />
  </ItemGroup>

  <ItemGroup>
    <None Include=".github\workflows\release.yml" />
  </ItemGroup>
</Project>
